# Site settings
title: LiWanwei's Blog
email: moth201236@163.com
description: > # this means to ignore newlines until "baseurl:"
  个人笔记，记录分享近期正在学习的东西，网站会慢慢优化，欢迎电邮交流。
baseurl: "/nopage" # the subpath of your site, e.g. /blog
url: "http://liwanwei.github.io" # the base hostname & protocol for your site

github_username:  liwanwei
weibo_username: 玩着玩着就伟大了

# Build settings
markdown: kramdown
